#!/bin/bash
# set -x

#----usage----#
usage(){
echo "$0, $INPUTDIR must be a valid dir which leads to BWF.WAV files generated by MixPre-3 MkII sound device's equipment"
local ERROR=$1
echo "ERROR:$ERROR"
exit
}

#----InputParameter

INPUTDIR=$1

#----Input Validation
[ -d $INPUTDIR ] && echo "input dir:$INPUTDIR is a valid folder" || usage "input dir:$INPUTDIR is not a valid dir"

#----List all .WAV files contained in INPUTDIR----#
LISTOFWAV=$(find $INPUTDIR | grep ".*\.WAV")
# if no found file => exit
[[ "$LISTOFWAV" == "" ]] && usage "No WAV files have been found in this dir:$INPUTDIR" || echo "$LISTOFWAV"

for WAV in $LISTOFWAV
do
  # path windows compatible
  WAVDISKNAME=$(echo "$WAV" | sed "s/\/cygdrive\/\([a-z]\)\/.*/\1/" | tr "[:lower:]" "[:upper:]")
  WAVDISKNAME="$WAVDISKNAME"":"
  WAVWINPATH=$(echo "$WAV" | sed "s/\/cygdrive\/[a-z]/$WAVDISKNAME/" )
  
  # Get old original file name
  OLDFILENAME=$(echo "$WAV" | sed "s/^.*\/\(.*\)\.WAV$/\1/")  
  # new  base file name based on sNOTE
  NEWFILENAME=$(ffprobe -loglevel -8 -show_entries "format_tags" "$WAVWINPATH" | grep "sNOTE=" | tr -d "\r" | sed "s/[^a-zA-Z0-9]/_/g" | tr " " "_" | tr "[:upper:]" "[:lower:]" | sed "s/_*$//" )
  NEWFILENAME=${NEWFILENAME:6}
  [[ $NEWFILENAME == "" ]] && NEWFILENAME="$OLDFILENAME"
    
  # Format value (stereo mono), Bitdepth value, samplerate value
  FORMATVALUE=$(ffprobe -loglevel -8 -show_entries "format_tags" "$WAVWINPATH" | grep "TAG:coding_history=" | tr -d "\r" | sed "s/.*,M=\([^,]*\),.*/\1/" )
    case $FORMATVALUE in
      "mono")FORMATSTR="M";;
    "stereo")FORMATSTR="ST";;
           *)FORMATSTR="X"  
  esac
  BITDEPTHVALUE=$(ffprobe -loglevel -8 -show_entries "format_tags" "$WAVWINPATH" | grep "TAG:coding_history=" | tr -d "\r" | sed "s/.*,W=\([0-9][0-9]\),.*/\1/" )
  SAMPLERATEVALUE=$(ffprobe -loglevel -8 -show_entries "format_tags" "$WAVWINPATH" | grep "TAG:coding_history=" | tr -d "\r" | sed "s/.*,F=\([0-9]*\),.*/\1/" | tr -d "0" )
  
  # concatenate
  OUTPUTFILENAME="$INPUTDIR""/""$NEWFILENAME"_"$FORMATSTR""$BITDEPTHVALUE""$SAMPLERATEVALUE"".WAV"

  # check for already existing file incrementing value "(_001.WAV) 
  if [ -f $OUTPUTFILENAME ]; then
    if [[ "$OUTPUTFILENAME" =~ .*_\([0-9][0-9][0-9]\)\.WAV ]]; then
      ORIGINALFILENUMBER=${BASH_REMATCH[1]}
      ((NEWFILENUMBER=ORIGINALFILENUMBER+1))
      NEWFILENUMBER=$(printf "%03d\n" $NEWFILENUMBER)
      OUTPUTFILENAME="$INPUTDIR""/""$NEWFILENAME"_"$FORMATSTR""$BITDEPTHVALUE""$SAMPLERATEVALUE""_""NEWFILENUMBER"".WAV"
      else
      OUTPUTFILENAME="$INPUTDIR""/""$NEWFILENAME"_"$FORMATSTR""$BITDEPTHVALUE""$SAMPLERATEVALUE""_002"".WAV"
    fi
  fi
  
  #rename
  mv $WAV $OUTPUTFILENAME
done
